=== Yanisrezgui/interpo-rabilit-php/xml/meteo.dtd
<!ELEMENT previsions (request_state, source,message,request_time,request_key,model_run,(echeance)*)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT request_time (#PCDATA)>
<!ELEMENT request_key (#PCDATA)>
<!ELEMENT request_state (#PCDATA)>
<!ELEMENT model_run (#PCDATA)>
<!ELEMENT echeance (temperature,pression,pluie,pluie_convective,humidite,vent_moyen,vent_rafales,vent_direction,iso_zero,risque_neige,cape,nebulosite)>
<!ELEMENT humidite (level)>
<!ELEMENT vent_moyen (level)>
<!ELEMENT vent_rafales (level)>
<!ELEMENT vent_direction (level)>
<!ELEMENT nebulosite (level)*>
<!ELEMENT pression (level)>
<!ELEMENT temperature (level)*>
<!ELEMENT level (#PCDATA)>
<!ELEMENT pluie (#PCDATA)>
<!ELEMENT pluie_convective (#PCDATA)>
<!ELEMENT iso_zero (#PCDATA)>
<!ELEMENT risque_neige (#PCDATA)>
<!ELEMENT cape (#PCDATA)>

<!ATTLIST level val CDATA #REQUIRED>
<!ATTLIST echeance hour CDATA #REQUIRED>
<!ATTLIST echeance timestamp CDATA #REQUIRED>
<!ATTLIST pluie interval CDATA #REQUIRED>
<!ATTLIST pluie_convective interval CDATA #REQUIRED>

=== Yanisrezgui/interpo-rabilit-php/xml/meteo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE previsions SYSTEM './meteo.dtd'>
<previsions>
  <request_state>200</request_state>
  <source>internal:GFS:1</source>
  <message>OK</message>
  <request_time>0.0071499347686768</request_time>
  <request_key>4deb4148245633f6e80aedd723f016d3</request_key>
  <model_run>07</model_run>
  <echeance hour="3" timestamp="2023-02-24 10:00:00 UTC">
    <temperature>
      <level val="2m">279.9</level>
      <level val="sol">281.2</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">101010</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">88.3</level>
    </humidite>
    <vent_moyen>
      <level val="10m">5.5</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">5.8</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">354</level>
    </vent_direction>
    <iso_zero>1760</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">22</level>
    </nebulosite>
  </echeance>
  <echeance hour="6" timestamp="2023-02-24 13:00:00 UTC">
    <temperature>
      <level val="2m">282.4</level>
      <level val="sol">283.6</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">100840</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">77.4</level>
    </humidite>
    <vent_moyen>
      <level val="10m">7.4</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">10.3</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">301</level>
    </vent_direction>
    <iso_zero>1834</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">44</level>
    </nebulosite>
  </echeance>
  <echeance hour="9" timestamp="2023-02-24 16:00:00 UTC">
    <temperature>
      <level val="2m">281</level>
      <level val="sol">282.9</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">100650</level>
    </pression>
    <pluie interval="3h">0.1</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">83.4</level>
    </humidite>
    <vent_moyen>
      <level val="10m">7.5</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">13</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">271</level>
    </vent_direction>
    <iso_zero>1748</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">100</level>
    </nebulosite>
  </echeance>
  <echeance hour="12" timestamp="2023-02-24 19:00:00 UTC">
    <temperature>
      <level val="2m">279.9</level>
      <level val="sol">281.8</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">100690</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0.1</pluie_convective>
    <humidite>
      <level val="2m">82.9</level>
    </humidite>
    <vent_moyen>
      <level val="10m">12.4</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">25.3</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">298</level>
    </vent_direction>
    <iso_zero>1656</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">96</level>
    </nebulosite>
  </echeance>
  <echeance hour="15" timestamp="2023-02-24 22:00:00 UTC">
    <temperature>
      <level val="2m">277.4</level>
      <level val="sol">279.3</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">100890</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">76.1</level>
    </humidite>
    <vent_moyen>
      <level val="10m">9.7</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">21</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">336</level>
    </vent_direction>
    <iso_zero>970</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">75</level>
    </nebulosite>
  </echeance>
  <echeance hour="18" timestamp="2023-02-25 01:00:00 UTC">
    <temperature>
      <level val="2m">276.3</level>
      <level val="sol">278.4</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">100960</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">85.3</level>
    </humidite>
    <vent_moyen>
      <level val="10m">8.7</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">20.9</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">304</level>
    </vent_direction>
    <iso_zero>890</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">79</level>
    </nebulosite>
  </echeance>
  <echeance hour="21" timestamp="2023-02-25 04:00:00 UTC">
    <temperature>
      <level val="2m">274.5</level>
      <level val="sol">276.5</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">101040</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">94</level>
    </humidite>
    <vent_moyen>
      <level val="10m">8.6</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">18.4</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">342</level>
    </vent_direction>
    <iso_zero>620</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">11</level>
    </nebulosite>
  </echeance>
  <echeance hour="24" timestamp="2023-02-25 07:00:00 UTC">
    <temperature>
      <level val="2m">273.2</level>
      <level val="sol">275.4</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">101130</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">91.9</level>
    </humidite>
    <vent_moyen>
      <level val="10m">5</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">5.5</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">326</level>
    </vent_direction>
    <iso_zero>431</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">13</level>
    </nebulosite>
  </echeance>
  <echeance hour="27" timestamp="2023-02-25 10:00:00 UTC">
    <temperature>
      <level val="2m">276.1</level>
      <level val="sol">277.2</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">101130</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">71.7</level>
    </humidite>
    <vent_moyen>
      <level val="10m">12.3</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">18.1</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">353</level>
    </vent_direction>
    <iso_zero>557</iso_zero>
    <risque_neige>non</risque_neige>
    <cape>0</cape>
    <nebulosite>
      <level val="haute">0</level>
      <level val="moyenne">0</level>
      <level val="basse">0</level>
      <level val="totale">17</level>
    </nebulosite>
  </echeance>
  <echeance hour="30" timestamp="2023-02-25 13:00:00 UTC">
    <temperature>
      <level val="2m">278.6</level>
      <level val="sol">279.5</level>
      <level val="850hPa">-0.1</level>
      <level val="500hPa">-0.1</level>
    </temperature>
    <pression>
      <level val="niveau_de_la_mer">101010</level>
    </pression>
    <pluie interval="3h">0</pluie>
    <pluie_convective interval="3h">0</pluie_convective>
    <humidite>
      <level val="2m">56.7</level>
    </humidite>
    <vent_moyen>
      <level val="10m">15.9</level>
    </vent_moyen>
    <vent_rafales>
      <level val="10m">18.9</level>
    </vent_rafales>
    <vent_direction>
      <level val="10m">360</level>
    </vent_direction>
    <iso_zero>766</iso_zero>
    <risque_neige>non</risque_neige>
